// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abuhggwssrxgdfyncril.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidWhnZ3dzc3J4Z2RmeW5jcmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODkyNDIsImV4cCI6MjA3Mjg2NTI0Mn0.lbODyEdFqs3J3EbpL80OOih0FTX8KNfpeBMA6RV9zDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});